Shader "Hidden/Amplify Color/MaskLinear" {
Properties {
 _MainTex ("Base (RGB)", 2D) = "" { }
}
SubShader { 
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  GpuProgramID 24162
Program "vp" {
SubProgram "d3d9 " {
Keywords { "AC_QUALITY_STANDARD" }
					"vs_2_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   float4 _MainTex_TexelSize;
					//   float4 _MaskTex_TexelSize;
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//   _MainTex_TexelSize c4       1
					//   _MaskTex_TexelSize c5       1
					//
					
					    vs_2_0
					    def c6, 0, -2, 1, 0
					    def c7, -0.5, 0.5, 0, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dp4 oPos.x, c0, v0
					    dp4 oPos.y, c1, v0
					    dp4 oPos.z, c2, v0
					    dp4 oPos.w, c3, v0
					    mov r0.x, c6.x
					    slt r0.x, c4.y, r0.x
					    mad r0.y, v1.y, c6.y, c6.z
					    mad r0.y, r0.x, r0.y, v1.y
					    mov r0.x, v1.x
					    mov r1.xy, c5
					    mad oT1.xy, r1, c7, r0
					    mov oT0.xy, v1
					
					// approximately 12 instruction slots used"
}
SubProgram "d3d11 " {
Keywords { "AC_QUALITY_STANDARD" }
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform VGlobals {
						vec4 unused_0_0[6];
						vec4 _MainTex_TexelSize;
						vec4 unused_0_2[2];
					};
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_1_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					 vec4 phase0_Output0_1;
					out vec2 vs_TEXCOORD1;
					vec4 u_xlat0;
					bool u_xlatb0;
					float u_xlat1;
					void main()
					{
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    u_xlatb0 = _MainTex_TexelSize.y<0.0;
					    u_xlat1 = (-in_TEXCOORD0.y) + 1.0;
					    phase0_Output0_1.w = (u_xlatb0) ? u_xlat1 : in_TEXCOORD0.y;
					    phase0_Output0_1.xyz = in_TEXCOORD0.xyx;
					vs_TEXCOORD0 = phase0_Output0_1.xy;
					vs_TEXCOORD1 = phase0_Output0_1.zw;
					    return;
					}"
}
SubProgram "d3d11_9x " {
Keywords { "AC_QUALITY_STANDARD" }
					"vs_4_0_level_9_1
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform VGlobals {
						vec4 unused_0_0[6];
						vec4 _MainTex_TexelSize;
						vec4 unused_0_2[2];
					};
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_1_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					 vec4 phase0_Output0_1;
					out vec2 vs_TEXCOORD1;
					vec4 u_xlat0;
					bool u_xlatb0;
					float u_xlat1;
					void main()
					{
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    u_xlatb0 = _MainTex_TexelSize.y<0.0;
					    u_xlat1 = (-in_TEXCOORD0.y) + 1.0;
					    phase0_Output0_1.w = (u_xlatb0) ? u_xlat1 : in_TEXCOORD0.y;
					    phase0_Output0_1.xyz = in_TEXCOORD0.xyx;
					vs_TEXCOORD0 = phase0_Output0_1.xy;
					vs_TEXCOORD1 = phase0_Output0_1.zw;
					    return;
					}"
}
SubProgram "d3d9 " {
Keywords { "AC_QUALITY_MOBILE" }
					"vs_2_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   float4 _MainTex_TexelSize;
					//   float4 _MaskTex_TexelSize;
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//   _MainTex_TexelSize c4       1
					//   _MaskTex_TexelSize c5       1
					//
					
					    vs_2_0
					    def c6, 0, -2, 1, 0
					    def c7, -0.5, 0.5, 0, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dp4 oPos.x, c0, v0
					    dp4 oPos.y, c1, v0
					    dp4 oPos.z, c2, v0
					    dp4 oPos.w, c3, v0
					    mov r0.x, c6.x
					    slt r0.x, c4.y, r0.x
					    mad r0.y, v1.y, c6.y, c6.z
					    mad r0.y, r0.x, r0.y, v1.y
					    mov r0.x, v1.x
					    mov r1.xy, c5
					    mad oT1.xy, r1, c7, r0
					    mov oT0.xy, v1
					
					// approximately 12 instruction slots used"
}
SubProgram "d3d11 " {
Keywords { "AC_QUALITY_MOBILE" }
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform VGlobals {
						vec4 unused_0_0[6];
						vec4 _MainTex_TexelSize;
						vec4 unused_0_2[2];
					};
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_1_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					 vec4 phase0_Output0_1;
					out vec2 vs_TEXCOORD1;
					vec4 u_xlat0;
					bool u_xlatb0;
					float u_xlat1;
					void main()
					{
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    u_xlatb0 = _MainTex_TexelSize.y<0.0;
					    u_xlat1 = (-in_TEXCOORD0.y) + 1.0;
					    phase0_Output0_1.w = (u_xlatb0) ? u_xlat1 : in_TEXCOORD0.y;
					    phase0_Output0_1.xyz = in_TEXCOORD0.xyx;
					vs_TEXCOORD0 = phase0_Output0_1.xy;
					vs_TEXCOORD1 = phase0_Output0_1.zw;
					    return;
					}"
}
SubProgram "d3d11_9x " {
Keywords { "AC_QUALITY_MOBILE" }
					"vs_4_0_level_9_1
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform VGlobals {
						vec4 unused_0_0[6];
						vec4 _MainTex_TexelSize;
						vec4 unused_0_2[2];
					};
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_1_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					 vec4 phase0_Output0_1;
					out vec2 vs_TEXCOORD1;
					vec4 u_xlat0;
					bool u_xlatb0;
					float u_xlat1;
					void main()
					{
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    u_xlatb0 = _MainTex_TexelSize.y<0.0;
					    u_xlat1 = (-in_TEXCOORD0.y) + 1.0;
					    phase0_Output0_1.w = (u_xlatb0) ? u_xlat1 : in_TEXCOORD0.y;
					    phase0_Output0_1.xyz = in_TEXCOORD0.xyx;
					vs_TEXCOORD0 = phase0_Output0_1.xy;
					vs_TEXCOORD1 = phase0_Output0_1.zw;
					    return;
					}"
}
}
Program "fp" {
SubProgram "d3d9 " {
Keywords { "AC_QUALITY_STANDARD" }
					"ps_2_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//   sampler2D _MaskTex;
					//   sampler2D _RgbTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//   _RgbTex      s1       1
					//   _MaskTex     s2       1
					//
					
					    ps_2_0
					    def c0, 1.05499995, -0.0549999997, 0, 0.03125
					    def c1, 0.0302734375, 0.96875, 31, 0.0404499993
					    def c2, -0.00313080009, 12.9200001, 0.416660011, 31
					    def c3, 0.00048828125, 0.015625, 0, 0.0773993805
					    def c4, 0.947867274, 0.0521326996, 2.4000001, 0
					    dcl t0.xy
					    dcl t1.xy
					    dcl_2d s0
					    dcl_2d s1
					    dcl_2d s2
					    texld_pp r0, t0, s0
					    log_pp r1.x, r0.x
					    log_pp r1.y, r0.y
					    log_pp r1.z, r0.z
					    mul_pp r1.xyz, r1, c2.z
					    exp_pp r2.x, r1.x
					    exp_pp r2.y, r1.y
					    exp_pp r2.z, r1.z
					    mad_pp r1.xyz, r2, c0.x, c0.y
					    add r2.xyz, r0, c2.x
					    mul_pp r3.xyz, r0, c2.y
					    cmp_pp r1.xyz, r2, r1, r3
					    mul r1.w, r1.z, c2.w
					    mov r2.xyz, c1
					    mad r1.xyz, r1, r2, c3
					    frc_pp r1.w, r1.w
					    add r1.z, -r1.w, r1.z
					    mad r1.xy, r1.z, c0.wzyx, r1
					    add r2.xy, r1, c0.wzyx
					    texld_pp r3, r1, s1
					    texld_pp r2, r2, s1
					    texld_pp r4, t1, s2
					    lrp_pp r4.yzw, r1.w, r2.wzyx, r3.wzyx
					    add r1.xyz, -r4.wzyx, c1.w
					    mul_pp r2.xyz, r4.wzyx, c3.w
					    mad_pp r3.xyz, r4.wzyx, c4.x, c4.y
					    log_pp r5.x, r3.x
					    log_pp r5.y, r3.y
					    log_pp r5.z, r3.z
					    mul_pp r3.xyz, r5, c4.z
					    exp_pp r5.x, r3.x
					    exp_pp r5.y, r3.y
					    exp_pp r5.z, r3.z
					    cmp_pp r1.xyz, r1, r2, r5
					    add_pp r1.xyz, -r0, r1
					    mov_pp r1.w, c0.z
					    mad_pp r0, r4.x, r1, r0
					    mov_pp oC0, r0
					
					// approximately 38 instruction slots used (4 texture, 34 arithmetic)"
}
SubProgram "d3d11 " {
Keywords { "AC_QUALITY_STANDARD" }
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					uniform  sampler2D _MainTex;
					uniform  sampler2D _MaskTex;
					uniform  sampler2D _RgbTex;
					in  vec2 vs_TEXCOORD0;
					in  vec2 vs_TEXCOORD1;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					bvec3 u_xlatb2;
					vec4 u_xlat3;
					bvec3 u_xlatb3;
					float u_xlat9;
					float u_xlat13;
					void main()
					{
					    u_xlat0 = texture(_MainTex, vs_TEXCOORD0.xy);
					    u_xlat1.xyz = log2(u_xlat0.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.416660011, 0.416660011, 0.416660011);
					    u_xlat1.xyz = exp2(u_xlat1.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(1.05499995, 1.05499995, 1.05499995) + vec3(-0.0549999997, -0.0549999997, -0.0549999997);
					    u_xlatb2.xyz = lessThan(u_xlat0.xyzx, vec4(0.00313080009, 0.00313080009, 0.00313080009, 0.0)).xyz;
					    u_xlat3.xyz = u_xlat0.xyz * vec3(12.9200001, 12.9200001, 12.9200001);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb2.x) ? u_xlat3.x : u_xlat1.x;
					        hlslcc_movcTemp.y = (u_xlatb2.y) ? u_xlat3.y : u_xlat1.y;
					        hlslcc_movcTemp.z = (u_xlatb2.z) ? u_xlat3.z : u_xlat1.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat13 = u_xlat1.z * 31.0;
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0302734375, 0.96875, 31.0) + vec3(0.00048828125, 0.015625, 0.0);
					    u_xlat13 = fract(u_xlat13);
					    u_xlat9 = (-u_xlat13) + u_xlat1.z;
					    u_xlat1.xy = vec2(u_xlat9) * vec2(0.03125, 0.0) + u_xlat1.xy;
					    u_xlat2.xy = u_xlat1.xy + vec2(0.03125, 0.0);
					    u_xlat3 = texture(_RgbTex, u_xlat1.xy);
					    u_xlat2 = texture(_RgbTex, u_xlat2.xy);
					    u_xlat1.xyz = (-u_xlat3.xyz) + u_xlat2.xyz;
					    u_xlat1.xyz = vec3(u_xlat13) * u_xlat1.xyz + u_xlat3.xyz;
					    u_xlat2.xyz = u_xlat1.xyz * vec3(0.947867274, 0.947867274, 0.947867274) + vec3(0.0521326996, 0.0521326996, 0.0521326996);
					    u_xlat2.xyz = log2(u_xlat2.xyz);
					    u_xlat2.xyz = u_xlat2.xyz * vec3(2.4000001, 2.4000001, 2.4000001);
					    u_xlat2.xyz = exp2(u_xlat2.xyz);
					    u_xlatb3.xyz = greaterThanEqual(vec4(0.0404499993, 0.0404499993, 0.0404499993, 0.0), u_xlat1.xyzx).xyz;
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0773993805, 0.0773993805, 0.0773993805);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb3.x) ? u_xlat1.x : u_xlat2.x;
					        hlslcc_movcTemp.y = (u_xlatb3.y) ? u_xlat1.y : u_xlat2.y;
					        hlslcc_movcTemp.z = (u_xlatb3.z) ? u_xlat1.z : u_xlat2.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat1.xyz = (-u_xlat0.xyz) + u_xlat1.xyz;
					    u_xlat2 = texture(_MaskTex, vs_TEXCOORD1.xy);
					    u_xlat1.w = 0.0;
					    SV_Target0 = u_xlat2.xxxx * u_xlat1 + u_xlat0;
					    return;
					}"
}
SubProgram "d3d11_9x " {
Keywords { "AC_QUALITY_STANDARD" }
					"ps_4_0_level_9_1
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					uniform  sampler2D _MainTex;
					uniform  sampler2D _MaskTex;
					uniform  sampler2D _RgbTex;
					in  vec2 vs_TEXCOORD0;
					in  vec2 vs_TEXCOORD1;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					bvec3 u_xlatb2;
					vec4 u_xlat3;
					bvec3 u_xlatb3;
					float u_xlat9;
					float u_xlat13;
					void main()
					{
					    u_xlat0 = texture(_MainTex, vs_TEXCOORD0.xy);
					    u_xlat1.xyz = log2(u_xlat0.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.416660011, 0.416660011, 0.416660011);
					    u_xlat1.xyz = exp2(u_xlat1.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(1.05499995, 1.05499995, 1.05499995) + vec3(-0.0549999997, -0.0549999997, -0.0549999997);
					    u_xlatb2.xyz = lessThan(u_xlat0.xyzx, vec4(0.00313080009, 0.00313080009, 0.00313080009, 0.0)).xyz;
					    u_xlat3.xyz = u_xlat0.xyz * vec3(12.9200001, 12.9200001, 12.9200001);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb2.x) ? u_xlat3.x : u_xlat1.x;
					        hlslcc_movcTemp.y = (u_xlatb2.y) ? u_xlat3.y : u_xlat1.y;
					        hlslcc_movcTemp.z = (u_xlatb2.z) ? u_xlat3.z : u_xlat1.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat13 = u_xlat1.z * 31.0;
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0302734375, 0.96875, 31.0) + vec3(0.00048828125, 0.015625, 0.0);
					    u_xlat13 = fract(u_xlat13);
					    u_xlat9 = (-u_xlat13) + u_xlat1.z;
					    u_xlat1.xy = vec2(u_xlat9) * vec2(0.03125, 0.0) + u_xlat1.xy;
					    u_xlat2.xy = u_xlat1.xy + vec2(0.03125, 0.0);
					    u_xlat3 = texture(_RgbTex, u_xlat1.xy);
					    u_xlat2 = texture(_RgbTex, u_xlat2.xy);
					    u_xlat1.xyz = (-u_xlat3.xyz) + u_xlat2.xyz;
					    u_xlat1.xyz = vec3(u_xlat13) * u_xlat1.xyz + u_xlat3.xyz;
					    u_xlat2.xyz = u_xlat1.xyz * vec3(0.947867274, 0.947867274, 0.947867274) + vec3(0.0521326996, 0.0521326996, 0.0521326996);
					    u_xlat2.xyz = log2(u_xlat2.xyz);
					    u_xlat2.xyz = u_xlat2.xyz * vec3(2.4000001, 2.4000001, 2.4000001);
					    u_xlat2.xyz = exp2(u_xlat2.xyz);
					    u_xlatb3.xyz = greaterThanEqual(vec4(0.0404499993, 0.0404499993, 0.0404499993, 0.0), u_xlat1.xyzx).xyz;
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0773993805, 0.0773993805, 0.0773993805);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb3.x) ? u_xlat1.x : u_xlat2.x;
					        hlslcc_movcTemp.y = (u_xlatb3.y) ? u_xlat1.y : u_xlat2.y;
					        hlslcc_movcTemp.z = (u_xlatb3.z) ? u_xlat1.z : u_xlat2.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat1.xyz = (-u_xlat0.xyz) + u_xlat1.xyz;
					    u_xlat2 = texture(_MaskTex, vs_TEXCOORD1.xy);
					    u_xlat1.w = 0.0;
					    SV_Target0 = u_xlat2.xxxx * u_xlat1 + u_xlat0;
					    return;
					}"
}
SubProgram "d3d9 " {
Keywords { "AC_QUALITY_MOBILE" }
					"ps_2_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//   sampler2D _MaskTex;
					//   sampler2D _RgbTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//   _RgbTex      s1       1
					//   _MaskTex     s2       1
					//
					
					    ps_2_0
					    def c0, 1.05499995, -0.0549999997, 0.96875, 0.0302734375
					    def c1, 0.00048828125, 0.015625, 31, 0.5
					    def c2, 0.03125, 0, 0.0773993805, 2.4000001
					    def c3, -0.00313080009, 12.9200001, 0.416660011, 0.0404499993
					    def c4, 0.947867274, 0.0521326996, 0, 0
					    dcl t0.xy
					    dcl t1.xy
					    dcl_2d s0
					    dcl_2d s1
					    dcl_2d s2
					    texld_pp r0, t0, s0
					    log_pp r1.x, r0.x
					    log_pp r1.y, r0.y
					    log_pp r1.z, r0.z
					    mul_pp r1.xyz, r1, c3.z
					    exp_pp r2.x, r1.x
					    exp_pp r2.y, r1.y
					    exp_pp r2.z, r1.z
					    mad_pp r1.xyz, r2, c0.x, c0.y
					    add r2.xyz, r0, c3.x
					    mul_pp r3.xyz, r0, c3.y
					    cmp_pp r1.xyz, r2, r1, r3
					    mad r1.z, r1.z, c1.z, c1.w
					    mov r2.zw, c0
					    mad r1.xy, r1, r2.wzyx, c1
					    frc r1.w, r1.z
					    add r1.z, -r1.w, r1.z
					    mad r1.xy, r1.z, c2, r1
					    texld_pp r1, r1, s1
					    texld_pp r2, t1, s2
					    add r2.yzw, -r1.wzyx, c3.w
					    mul_pp r3.xyz, r1, c2.z
					    mad_pp r1.xyz, r1, c4.x, c4.y
					    log_pp r4.x, r1.x
					    log_pp r4.y, r1.y
					    log_pp r4.z, r1.z
					    mul_pp r1.xyz, r4, c2.w
					    exp_pp r4.x, r1.x
					    exp_pp r4.y, r1.y
					    exp_pp r4.z, r1.z
					    cmp_pp r1.xyz, r2.wzyx, r3, r4
					    add_pp r1.xyz, -r0, r1
					    mov_pp r1.w, c2.y
					    mad_pp r0, r2.x, r1, r0
					    mov_pp oC0, r0
					
					// approximately 35 instruction slots used (3 texture, 32 arithmetic)"
}
SubProgram "d3d11 " {
Keywords { "AC_QUALITY_MOBILE" }
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					uniform  sampler2D _MainTex;
					uniform  sampler2D _MaskTex;
					uniform  sampler2D _RgbTex;
					in  vec2 vs_TEXCOORD0;
					in  vec2 vs_TEXCOORD1;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					bvec3 u_xlatb2;
					vec3 u_xlat3;
					bvec3 u_xlatb3;
					float u_xlat9;
					void main()
					{
					    u_xlat0 = texture(_MainTex, vs_TEXCOORD0.xy);
					    u_xlat1.xyz = log2(u_xlat0.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.416660011, 0.416660011, 0.416660011);
					    u_xlat1.xyz = exp2(u_xlat1.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(1.05499995, 1.05499995, 1.05499995) + vec3(-0.0549999997, -0.0549999997, -0.0549999997);
					    u_xlatb2.xyz = lessThan(u_xlat0.xyzx, vec4(0.00313080009, 0.00313080009, 0.00313080009, 0.0)).xyz;
					    u_xlat3.xyz = u_xlat0.xyz * vec3(12.9200001, 12.9200001, 12.9200001);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb2.x) ? u_xlat3.x : u_xlat1.x;
					        hlslcc_movcTemp.y = (u_xlatb2.y) ? u_xlat3.y : u_xlat1.y;
					        hlslcc_movcTemp.z = (u_xlatb2.z) ? u_xlat3.z : u_xlat1.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0302734375, 0.96875, 31.0) + vec3(0.00048828125, 0.015625, 0.5);
					    u_xlat9 = floor(u_xlat1.z);
					    u_xlat1.xy = vec2(u_xlat9) * vec2(0.03125, 0.0) + u_xlat1.xy;
					    u_xlat1 = texture(_RgbTex, u_xlat1.xy);
					    u_xlat2.xyz = u_xlat1.xyz * vec3(0.947867274, 0.947867274, 0.947867274) + vec3(0.0521326996, 0.0521326996, 0.0521326996);
					    u_xlat2.xyz = log2(u_xlat2.xyz);
					    u_xlat2.xyz = u_xlat2.xyz * vec3(2.4000001, 2.4000001, 2.4000001);
					    u_xlat2.xyz = exp2(u_xlat2.xyz);
					    u_xlatb3.xyz = greaterThanEqual(vec4(0.0404499993, 0.0404499993, 0.0404499993, 0.0), u_xlat1.xyzx).xyz;
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0773993805, 0.0773993805, 0.0773993805);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb3.x) ? u_xlat1.x : u_xlat2.x;
					        hlslcc_movcTemp.y = (u_xlatb3.y) ? u_xlat1.y : u_xlat2.y;
					        hlslcc_movcTemp.z = (u_xlatb3.z) ? u_xlat1.z : u_xlat2.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat1.xyz = (-u_xlat0.xyz) + u_xlat1.xyz;
					    u_xlat2 = texture(_MaskTex, vs_TEXCOORD1.xy);
					    u_xlat1.w = 0.0;
					    SV_Target0 = u_xlat2.xxxx * u_xlat1 + u_xlat0;
					    return;
					}"
}
SubProgram "d3d11_9x " {
Keywords { "AC_QUALITY_MOBILE" }
					"ps_4_0_level_9_1
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					uniform  sampler2D _MainTex;
					uniform  sampler2D _MaskTex;
					uniform  sampler2D _RgbTex;
					in  vec2 vs_TEXCOORD0;
					in  vec2 vs_TEXCOORD1;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					bvec3 u_xlatb2;
					vec3 u_xlat3;
					bvec3 u_xlatb3;
					float u_xlat9;
					void main()
					{
					    u_xlat0 = texture(_MainTex, vs_TEXCOORD0.xy);
					    u_xlat1.xyz = log2(u_xlat0.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.416660011, 0.416660011, 0.416660011);
					    u_xlat1.xyz = exp2(u_xlat1.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(1.05499995, 1.05499995, 1.05499995) + vec3(-0.0549999997, -0.0549999997, -0.0549999997);
					    u_xlatb2.xyz = lessThan(u_xlat0.xyzx, vec4(0.00313080009, 0.00313080009, 0.00313080009, 0.0)).xyz;
					    u_xlat3.xyz = u_xlat0.xyz * vec3(12.9200001, 12.9200001, 12.9200001);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb2.x) ? u_xlat3.x : u_xlat1.x;
					        hlslcc_movcTemp.y = (u_xlatb2.y) ? u_xlat3.y : u_xlat1.y;
					        hlslcc_movcTemp.z = (u_xlatb2.z) ? u_xlat3.z : u_xlat1.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0302734375, 0.96875, 31.0) + vec3(0.00048828125, 0.015625, 0.5);
					    u_xlat9 = floor(u_xlat1.z);
					    u_xlat1.xy = vec2(u_xlat9) * vec2(0.03125, 0.0) + u_xlat1.xy;
					    u_xlat1 = texture(_RgbTex, u_xlat1.xy);
					    u_xlat2.xyz = u_xlat1.xyz * vec3(0.947867274, 0.947867274, 0.947867274) + vec3(0.0521326996, 0.0521326996, 0.0521326996);
					    u_xlat2.xyz = log2(u_xlat2.xyz);
					    u_xlat2.xyz = u_xlat2.xyz * vec3(2.4000001, 2.4000001, 2.4000001);
					    u_xlat2.xyz = exp2(u_xlat2.xyz);
					    u_xlatb3.xyz = greaterThanEqual(vec4(0.0404499993, 0.0404499993, 0.0404499993, 0.0), u_xlat1.xyzx).xyz;
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0773993805, 0.0773993805, 0.0773993805);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb3.x) ? u_xlat1.x : u_xlat2.x;
					        hlslcc_movcTemp.y = (u_xlatb3.y) ? u_xlat1.y : u_xlat2.y;
					        hlslcc_movcTemp.z = (u_xlatb3.z) ? u_xlat1.z : u_xlat2.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat1.xyz = (-u_xlat0.xyz) + u_xlat1.xyz;
					    u_xlat2 = texture(_MaskTex, vs_TEXCOORD1.xy);
					    u_xlat1.w = 0.0;
					    SV_Target0 = u_xlat2.xxxx * u_xlat1 + u_xlat0;
					    return;
					}"
}
}
 }
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  GpuProgramID 91593
Program "vp" {
SubProgram "d3d9 " {
Keywords { "AC_QUALITY_STANDARD" }
					"vs_2_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   float4 _MainTex_TexelSize;
					//   float4 _MaskTex_TexelSize;
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//   _MainTex_TexelSize c4       1
					//   _MaskTex_TexelSize c5       1
					//
					
					    vs_2_0
					    def c6, 0, -2, 1, 0
					    def c7, -0.5, 0.5, 0, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dp4 oPos.x, c0, v0
					    dp4 oPos.y, c1, v0
					    dp4 oPos.z, c2, v0
					    dp4 oPos.w, c3, v0
					    mov r0.x, c6.x
					    slt r0.x, c4.y, r0.x
					    mad r0.y, v1.y, c6.y, c6.z
					    mad r0.y, r0.x, r0.y, v1.y
					    mov r0.x, v1.x
					    mov r1.xy, c5
					    mad oT1.xy, r1, c7, r0
					    mov oT0.xy, v1
					
					// approximately 12 instruction slots used"
}
SubProgram "d3d11 " {
Keywords { "AC_QUALITY_STANDARD" }
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform VGlobals {
						vec4 unused_0_0[6];
						vec4 _MainTex_TexelSize;
						vec4 unused_0_2[2];
					};
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_1_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					 vec4 phase0_Output0_1;
					out vec2 vs_TEXCOORD1;
					vec4 u_xlat0;
					bool u_xlatb0;
					float u_xlat1;
					void main()
					{
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    u_xlatb0 = _MainTex_TexelSize.y<0.0;
					    u_xlat1 = (-in_TEXCOORD0.y) + 1.0;
					    phase0_Output0_1.w = (u_xlatb0) ? u_xlat1 : in_TEXCOORD0.y;
					    phase0_Output0_1.xyz = in_TEXCOORD0.xyx;
					vs_TEXCOORD0 = phase0_Output0_1.xy;
					vs_TEXCOORD1 = phase0_Output0_1.zw;
					    return;
					}"
}
SubProgram "d3d11_9x " {
Keywords { "AC_QUALITY_STANDARD" }
					"vs_4_0_level_9_1
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform VGlobals {
						vec4 unused_0_0[6];
						vec4 _MainTex_TexelSize;
						vec4 unused_0_2[2];
					};
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_1_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					 vec4 phase0_Output0_1;
					out vec2 vs_TEXCOORD1;
					vec4 u_xlat0;
					bool u_xlatb0;
					float u_xlat1;
					void main()
					{
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    u_xlatb0 = _MainTex_TexelSize.y<0.0;
					    u_xlat1 = (-in_TEXCOORD0.y) + 1.0;
					    phase0_Output0_1.w = (u_xlatb0) ? u_xlat1 : in_TEXCOORD0.y;
					    phase0_Output0_1.xyz = in_TEXCOORD0.xyx;
					vs_TEXCOORD0 = phase0_Output0_1.xy;
					vs_TEXCOORD1 = phase0_Output0_1.zw;
					    return;
					}"
}
SubProgram "d3d9 " {
Keywords { "AC_QUALITY_MOBILE" }
					"vs_2_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   float4 _MainTex_TexelSize;
					//   float4 _MaskTex_TexelSize;
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//   _MainTex_TexelSize c4       1
					//   _MaskTex_TexelSize c5       1
					//
					
					    vs_2_0
					    def c6, 0, -2, 1, 0
					    def c7, -0.5, 0.5, 0, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dp4 oPos.x, c0, v0
					    dp4 oPos.y, c1, v0
					    dp4 oPos.z, c2, v0
					    dp4 oPos.w, c3, v0
					    mov r0.x, c6.x
					    slt r0.x, c4.y, r0.x
					    mad r0.y, v1.y, c6.y, c6.z
					    mad r0.y, r0.x, r0.y, v1.y
					    mov r0.x, v1.x
					    mov r1.xy, c5
					    mad oT1.xy, r1, c7, r0
					    mov oT0.xy, v1
					
					// approximately 12 instruction slots used"
}
SubProgram "d3d11 " {
Keywords { "AC_QUALITY_MOBILE" }
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform VGlobals {
						vec4 unused_0_0[6];
						vec4 _MainTex_TexelSize;
						vec4 unused_0_2[2];
					};
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_1_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					 vec4 phase0_Output0_1;
					out vec2 vs_TEXCOORD1;
					vec4 u_xlat0;
					bool u_xlatb0;
					float u_xlat1;
					void main()
					{
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    u_xlatb0 = _MainTex_TexelSize.y<0.0;
					    u_xlat1 = (-in_TEXCOORD0.y) + 1.0;
					    phase0_Output0_1.w = (u_xlatb0) ? u_xlat1 : in_TEXCOORD0.y;
					    phase0_Output0_1.xyz = in_TEXCOORD0.xyx;
					vs_TEXCOORD0 = phase0_Output0_1.xy;
					vs_TEXCOORD1 = phase0_Output0_1.zw;
					    return;
					}"
}
SubProgram "d3d11_9x " {
Keywords { "AC_QUALITY_MOBILE" }
					"vs_4_0_level_9_1
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform VGlobals {
						vec4 unused_0_0[6];
						vec4 _MainTex_TexelSize;
						vec4 unused_0_2[2];
					};
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_1_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					 vec4 phase0_Output0_1;
					out vec2 vs_TEXCOORD1;
					vec4 u_xlat0;
					bool u_xlatb0;
					float u_xlat1;
					void main()
					{
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    u_xlatb0 = _MainTex_TexelSize.y<0.0;
					    u_xlat1 = (-in_TEXCOORD0.y) + 1.0;
					    phase0_Output0_1.w = (u_xlatb0) ? u_xlat1 : in_TEXCOORD0.y;
					    phase0_Output0_1.xyz = in_TEXCOORD0.xyx;
					vs_TEXCOORD0 = phase0_Output0_1.xy;
					vs_TEXCOORD1 = phase0_Output0_1.zw;
					    return;
					}"
}
}
Program "fp" {
SubProgram "d3d9 " {
Keywords { "AC_QUALITY_STANDARD" }
					"ps_2_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//   sampler2D _MaskTex;
					//   sampler2D _RgbTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//   _RgbTex      s1       1
					//   _MaskTex     s2       1
					//
					
					    ps_2_0
					    def c0, 1, -0.00313080009, 12.9200001, 0.416660011
					    def c1, 1.05499995, -0.0549999997, 31, 0.0404499993
					    def c2, 0.0302734375, 0.96875, 31, 0.0773993805
					    def c3, 0.00048828125, 0.015625, 0, 0.03125
					    def c4, 0.947867274, 0.0521326996, 2.4000001, 0
					    dcl t0.xy
					    dcl t1.xy
					    dcl_2d s0
					    dcl_2d s1
					    dcl_2d s2
					    texld_pp r0, t0, s0
					    min_pp r1, r0, c0.x
					    log_pp r0.x, r1.x
					    log_pp r0.y, r1.y
					    log_pp r0.z, r1.z
					    mul_pp r0.xyz, r0, c0.w
					    exp_pp r2.x, r0.x
					    exp_pp r2.y, r0.y
					    exp_pp r2.z, r0.z
					    mad_pp r0.xyz, r2, c1.x, c1.y
					    add r2.xyz, r1, c0.y
					    mul_pp r3.xyz, r1, c0.z
					    cmp_pp r0.xyz, r2, r0, r3
					    mul r0.w, r0.z, c1.z
					    mov r2.xyz, c3
					    mad r0.xyz, r0, c2, r2
					    frc_pp r0.w, r0.w
					    add r0.z, -r0.w, r0.z
					    mad r0.xy, r0.z, c3.wzyx, r0
					    add r2.xy, r0, c3.wzyx
					    texld_pp r3, r0, s1
					    texld_pp r2, r2, s1
					    texld_pp r4, t1, s2
					    lrp_pp r4.yzw, r0.w, r2.wzyx, r3.wzyx
					    add r0.xyz, -r4.wzyx, c1.w
					    mul_pp r2.xyz, r4.wzyx, c2.w
					    mad_pp r3.xyz, r4.wzyx, c4.x, c4.y
					    log_pp r5.x, r3.x
					    log_pp r5.y, r3.y
					    log_pp r5.z, r3.z
					    mul_pp r3.xyz, r5, c4.z
					    exp_pp r5.x, r3.x
					    exp_pp r5.y, r3.y
					    exp_pp r5.z, r3.z
					    cmp_pp r0.xyz, r0, r2, r5
					    add_pp r0.xyz, -r1, r0
					    mov_pp r0.w, c3.z
					    mad_pp r0, r4.x, r0, r1
					    mov_pp oC0, r0
					
					// approximately 39 instruction slots used (4 texture, 35 arithmetic)"
}
SubProgram "d3d11 " {
Keywords { "AC_QUALITY_STANDARD" }
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					uniform  sampler2D _MainTex;
					uniform  sampler2D _MaskTex;
					uniform  sampler2D _RgbTex;
					in  vec2 vs_TEXCOORD0;
					in  vec2 vs_TEXCOORD1;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					bvec3 u_xlatb2;
					vec4 u_xlat3;
					bvec3 u_xlatb3;
					float u_xlat9;
					float u_xlat13;
					void main()
					{
					    u_xlat0 = texture(_MainTex, vs_TEXCOORD0.xy);
					    u_xlat0 = u_xlat0;
					    u_xlat0 = clamp(u_xlat0, 0.0, 1.0);
					    u_xlat1.xyz = log2(u_xlat0.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.416660011, 0.416660011, 0.416660011);
					    u_xlat1.xyz = exp2(u_xlat1.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(1.05499995, 1.05499995, 1.05499995) + vec3(-0.0549999997, -0.0549999997, -0.0549999997);
					    u_xlatb2.xyz = lessThan(u_xlat0.xyzx, vec4(0.00313080009, 0.00313080009, 0.00313080009, 0.0)).xyz;
					    u_xlat3.xyz = u_xlat0.xyz * vec3(12.9200001, 12.9200001, 12.9200001);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb2.x) ? u_xlat3.x : u_xlat1.x;
					        hlslcc_movcTemp.y = (u_xlatb2.y) ? u_xlat3.y : u_xlat1.y;
					        hlslcc_movcTemp.z = (u_xlatb2.z) ? u_xlat3.z : u_xlat1.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat13 = u_xlat1.z * 31.0;
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0302734375, 0.96875, 31.0) + vec3(0.00048828125, 0.015625, 0.0);
					    u_xlat13 = fract(u_xlat13);
					    u_xlat9 = (-u_xlat13) + u_xlat1.z;
					    u_xlat1.xy = vec2(u_xlat9) * vec2(0.03125, 0.0) + u_xlat1.xy;
					    u_xlat2.xy = u_xlat1.xy + vec2(0.03125, 0.0);
					    u_xlat3 = texture(_RgbTex, u_xlat1.xy);
					    u_xlat2 = texture(_RgbTex, u_xlat2.xy);
					    u_xlat1.xyz = (-u_xlat3.xyz) + u_xlat2.xyz;
					    u_xlat1.xyz = vec3(u_xlat13) * u_xlat1.xyz + u_xlat3.xyz;
					    u_xlat2.xyz = u_xlat1.xyz * vec3(0.947867274, 0.947867274, 0.947867274) + vec3(0.0521326996, 0.0521326996, 0.0521326996);
					    u_xlat2.xyz = log2(u_xlat2.xyz);
					    u_xlat2.xyz = u_xlat2.xyz * vec3(2.4000001, 2.4000001, 2.4000001);
					    u_xlat2.xyz = exp2(u_xlat2.xyz);
					    u_xlatb3.xyz = greaterThanEqual(vec4(0.0404499993, 0.0404499993, 0.0404499993, 0.0), u_xlat1.xyzx).xyz;
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0773993805, 0.0773993805, 0.0773993805);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb3.x) ? u_xlat1.x : u_xlat2.x;
					        hlslcc_movcTemp.y = (u_xlatb3.y) ? u_xlat1.y : u_xlat2.y;
					        hlslcc_movcTemp.z = (u_xlatb3.z) ? u_xlat1.z : u_xlat2.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat1.xyz = (-u_xlat0.xyz) + u_xlat1.xyz;
					    u_xlat2 = texture(_MaskTex, vs_TEXCOORD1.xy);
					    u_xlat1.w = 0.0;
					    SV_Target0 = u_xlat2.xxxx * u_xlat1 + u_xlat0;
					    return;
					}"
}
SubProgram "d3d11_9x " {
Keywords { "AC_QUALITY_STANDARD" }
					"ps_4_0_level_9_1
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					uniform  sampler2D _MainTex;
					uniform  sampler2D _MaskTex;
					uniform  sampler2D _RgbTex;
					in  vec2 vs_TEXCOORD0;
					in  vec2 vs_TEXCOORD1;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					bvec3 u_xlatb2;
					vec4 u_xlat3;
					bvec3 u_xlatb3;
					float u_xlat9;
					float u_xlat13;
					void main()
					{
					    u_xlat0 = texture(_MainTex, vs_TEXCOORD0.xy);
					    u_xlat0 = u_xlat0;
					    u_xlat0 = clamp(u_xlat0, 0.0, 1.0);
					    u_xlat1.xyz = log2(u_xlat0.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.416660011, 0.416660011, 0.416660011);
					    u_xlat1.xyz = exp2(u_xlat1.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(1.05499995, 1.05499995, 1.05499995) + vec3(-0.0549999997, -0.0549999997, -0.0549999997);
					    u_xlatb2.xyz = lessThan(u_xlat0.xyzx, vec4(0.00313080009, 0.00313080009, 0.00313080009, 0.0)).xyz;
					    u_xlat3.xyz = u_xlat0.xyz * vec3(12.9200001, 12.9200001, 12.9200001);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb2.x) ? u_xlat3.x : u_xlat1.x;
					        hlslcc_movcTemp.y = (u_xlatb2.y) ? u_xlat3.y : u_xlat1.y;
					        hlslcc_movcTemp.z = (u_xlatb2.z) ? u_xlat3.z : u_xlat1.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat13 = u_xlat1.z * 31.0;
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0302734375, 0.96875, 31.0) + vec3(0.00048828125, 0.015625, 0.0);
					    u_xlat13 = fract(u_xlat13);
					    u_xlat9 = (-u_xlat13) + u_xlat1.z;
					    u_xlat1.xy = vec2(u_xlat9) * vec2(0.03125, 0.0) + u_xlat1.xy;
					    u_xlat2.xy = u_xlat1.xy + vec2(0.03125, 0.0);
					    u_xlat3 = texture(_RgbTex, u_xlat1.xy);
					    u_xlat2 = texture(_RgbTex, u_xlat2.xy);
					    u_xlat1.xyz = (-u_xlat3.xyz) + u_xlat2.xyz;
					    u_xlat1.xyz = vec3(u_xlat13) * u_xlat1.xyz + u_xlat3.xyz;
					    u_xlat2.xyz = u_xlat1.xyz * vec3(0.947867274, 0.947867274, 0.947867274) + vec3(0.0521326996, 0.0521326996, 0.0521326996);
					    u_xlat2.xyz = log2(u_xlat2.xyz);
					    u_xlat2.xyz = u_xlat2.xyz * vec3(2.4000001, 2.4000001, 2.4000001);
					    u_xlat2.xyz = exp2(u_xlat2.xyz);
					    u_xlatb3.xyz = greaterThanEqual(vec4(0.0404499993, 0.0404499993, 0.0404499993, 0.0), u_xlat1.xyzx).xyz;
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0773993805, 0.0773993805, 0.0773993805);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb3.x) ? u_xlat1.x : u_xlat2.x;
					        hlslcc_movcTemp.y = (u_xlatb3.y) ? u_xlat1.y : u_xlat2.y;
					        hlslcc_movcTemp.z = (u_xlatb3.z) ? u_xlat1.z : u_xlat2.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat1.xyz = (-u_xlat0.xyz) + u_xlat1.xyz;
					    u_xlat2 = texture(_MaskTex, vs_TEXCOORD1.xy);
					    u_xlat1.w = 0.0;
					    SV_Target0 = u_xlat2.xxxx * u_xlat1 + u_xlat0;
					    return;
					}"
}
SubProgram "d3d9 " {
Keywords { "AC_QUALITY_MOBILE" }
					"ps_2_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//   sampler2D _MaskTex;
					//   sampler2D _RgbTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//   _RgbTex      s1       1
					//   _MaskTex     s2       1
					//
					
					    ps_2_0
					    def c0, 1, -0.00313080009, 12.9200001, 0.416660011
					    def c1, 1.05499995, -0.0549999997, 0.96875, 0.0302734375
					    def c2, 0.00048828125, 0.015625, 31, 0.5
					    def c3, 0.03125, 0, 0.0404499993, 0.0773993805
					    def c4, 0.947867274, 0.0521326996, 2.4000001, 0
					    dcl t0.xy
					    dcl t1.xy
					    dcl_2d s0
					    dcl_2d s1
					    dcl_2d s2
					    texld_pp r0, t0, s0
					    min_pp r1, r0, c0.x
					    log_pp r0.x, r1.x
					    log_pp r0.y, r1.y
					    log_pp r0.z, r1.z
					    mul_pp r0.xyz, r0, c0.w
					    exp_pp r2.x, r0.x
					    exp_pp r2.y, r0.y
					    exp_pp r2.z, r0.z
					    mad_pp r0.xyz, r2, c1.x, c1.y
					    add r2.xyz, r1, c0.y
					    mul_pp r3.xyz, r1, c0.z
					    cmp_pp r0.xyz, r2, r0, r3
					    mad r0.z, r0.z, c2.z, c2.w
					    mov r2.zw, c1
					    mad r0.xy, r0, r2.wzyx, c2
					    frc r0.w, r0.z
					    add r0.z, -r0.w, r0.z
					    mad r0.xy, r0.z, c3, r0
					    texld_pp r0, r0, s1
					    texld_pp r2, t1, s2
					    add r2.yzw, -r0.wzyx, c3.z
					    mul_pp r3.xyz, r0, c3.w
					    mad_pp r0.xyz, r0, c4.x, c4.y
					    log_pp r4.x, r0.x
					    log_pp r4.y, r0.y
					    log_pp r4.z, r0.z
					    mul_pp r0.xyz, r4, c4.z
					    exp_pp r4.x, r0.x
					    exp_pp r4.y, r0.y
					    exp_pp r4.z, r0.z
					    cmp_pp r0.xyz, r2.wzyx, r3, r4
					    add_pp r0.xyz, -r1, r0
					    mov_pp r0.w, c3.y
					    mad_pp r0, r2.x, r0, r1
					    mov_pp oC0, r0
					
					// approximately 36 instruction slots used (3 texture, 33 arithmetic)"
}
SubProgram "d3d11 " {
Keywords { "AC_QUALITY_MOBILE" }
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					uniform  sampler2D _MainTex;
					uniform  sampler2D _MaskTex;
					uniform  sampler2D _RgbTex;
					in  vec2 vs_TEXCOORD0;
					in  vec2 vs_TEXCOORD1;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					bvec3 u_xlatb2;
					vec3 u_xlat3;
					bvec3 u_xlatb3;
					float u_xlat9;
					void main()
					{
					    u_xlat0 = texture(_MainTex, vs_TEXCOORD0.xy);
					    u_xlat0 = u_xlat0;
					    u_xlat0 = clamp(u_xlat0, 0.0, 1.0);
					    u_xlat1.xyz = log2(u_xlat0.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.416660011, 0.416660011, 0.416660011);
					    u_xlat1.xyz = exp2(u_xlat1.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(1.05499995, 1.05499995, 1.05499995) + vec3(-0.0549999997, -0.0549999997, -0.0549999997);
					    u_xlatb2.xyz = lessThan(u_xlat0.xyzx, vec4(0.00313080009, 0.00313080009, 0.00313080009, 0.0)).xyz;
					    u_xlat3.xyz = u_xlat0.xyz * vec3(12.9200001, 12.9200001, 12.9200001);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb2.x) ? u_xlat3.x : u_xlat1.x;
					        hlslcc_movcTemp.y = (u_xlatb2.y) ? u_xlat3.y : u_xlat1.y;
					        hlslcc_movcTemp.z = (u_xlatb2.z) ? u_xlat3.z : u_xlat1.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0302734375, 0.96875, 31.0) + vec3(0.00048828125, 0.015625, 0.5);
					    u_xlat9 = floor(u_xlat1.z);
					    u_xlat1.xy = vec2(u_xlat9) * vec2(0.03125, 0.0) + u_xlat1.xy;
					    u_xlat1 = texture(_RgbTex, u_xlat1.xy);
					    u_xlat2.xyz = u_xlat1.xyz * vec3(0.947867274, 0.947867274, 0.947867274) + vec3(0.0521326996, 0.0521326996, 0.0521326996);
					    u_xlat2.xyz = log2(u_xlat2.xyz);
					    u_xlat2.xyz = u_xlat2.xyz * vec3(2.4000001, 2.4000001, 2.4000001);
					    u_xlat2.xyz = exp2(u_xlat2.xyz);
					    u_xlatb3.xyz = greaterThanEqual(vec4(0.0404499993, 0.0404499993, 0.0404499993, 0.0), u_xlat1.xyzx).xyz;
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0773993805, 0.0773993805, 0.0773993805);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb3.x) ? u_xlat1.x : u_xlat2.x;
					        hlslcc_movcTemp.y = (u_xlatb3.y) ? u_xlat1.y : u_xlat2.y;
					        hlslcc_movcTemp.z = (u_xlatb3.z) ? u_xlat1.z : u_xlat2.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat1.xyz = (-u_xlat0.xyz) + u_xlat1.xyz;
					    u_xlat2 = texture(_MaskTex, vs_TEXCOORD1.xy);
					    u_xlat1.w = 0.0;
					    SV_Target0 = u_xlat2.xxxx * u_xlat1 + u_xlat0;
					    return;
					}"
}
SubProgram "d3d11_9x " {
Keywords { "AC_QUALITY_MOBILE" }
					"ps_4_0_level_9_1
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					uniform  sampler2D _MainTex;
					uniform  sampler2D _MaskTex;
					uniform  sampler2D _RgbTex;
					in  vec2 vs_TEXCOORD0;
					in  vec2 vs_TEXCOORD1;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					bvec3 u_xlatb2;
					vec3 u_xlat3;
					bvec3 u_xlatb3;
					float u_xlat9;
					void main()
					{
					    u_xlat0 = texture(_MainTex, vs_TEXCOORD0.xy);
					    u_xlat0 = u_xlat0;
					    u_xlat0 = clamp(u_xlat0, 0.0, 1.0);
					    u_xlat1.xyz = log2(u_xlat0.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.416660011, 0.416660011, 0.416660011);
					    u_xlat1.xyz = exp2(u_xlat1.xyz);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(1.05499995, 1.05499995, 1.05499995) + vec3(-0.0549999997, -0.0549999997, -0.0549999997);
					    u_xlatb2.xyz = lessThan(u_xlat0.xyzx, vec4(0.00313080009, 0.00313080009, 0.00313080009, 0.0)).xyz;
					    u_xlat3.xyz = u_xlat0.xyz * vec3(12.9200001, 12.9200001, 12.9200001);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb2.x) ? u_xlat3.x : u_xlat1.x;
					        hlslcc_movcTemp.y = (u_xlatb2.y) ? u_xlat3.y : u_xlat1.y;
					        hlslcc_movcTemp.z = (u_xlatb2.z) ? u_xlat3.z : u_xlat1.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0302734375, 0.96875, 31.0) + vec3(0.00048828125, 0.015625, 0.5);
					    u_xlat9 = floor(u_xlat1.z);
					    u_xlat1.xy = vec2(u_xlat9) * vec2(0.03125, 0.0) + u_xlat1.xy;
					    u_xlat1 = texture(_RgbTex, u_xlat1.xy);
					    u_xlat2.xyz = u_xlat1.xyz * vec3(0.947867274, 0.947867274, 0.947867274) + vec3(0.0521326996, 0.0521326996, 0.0521326996);
					    u_xlat2.xyz = log2(u_xlat2.xyz);
					    u_xlat2.xyz = u_xlat2.xyz * vec3(2.4000001, 2.4000001, 2.4000001);
					    u_xlat2.xyz = exp2(u_xlat2.xyz);
					    u_xlatb3.xyz = greaterThanEqual(vec4(0.0404499993, 0.0404499993, 0.0404499993, 0.0), u_xlat1.xyzx).xyz;
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.0773993805, 0.0773993805, 0.0773993805);
					    {
					        vec4 hlslcc_movcTemp = u_xlat1;
					        hlslcc_movcTemp.x = (u_xlatb3.x) ? u_xlat1.x : u_xlat2.x;
					        hlslcc_movcTemp.y = (u_xlatb3.y) ? u_xlat1.y : u_xlat2.y;
					        hlslcc_movcTemp.z = (u_xlatb3.z) ? u_xlat1.z : u_xlat2.z;
					        u_xlat1 = hlslcc_movcTemp;
					    }
					    u_xlat1.xyz = (-u_xlat0.xyz) + u_xlat1.xyz;
					    u_xlat2 = texture(_MaskTex, vs_TEXCOORD1.xy);
					    u_xlat1.w = 0.0;
					    SV_Target0 = u_xlat2.xxxx * u_xlat1 + u_xlat0;
					    return;
					}"
}
}
 }
}
Fallback Off
}